Module4 task1
htmlacademy-javascript/1631267-keksobooking-23 pull request #3
Opened 2021-06-07 11:17 UTC by Konstantin9658

Привет! В комментариях написал, где возникают у меня проблемы, не совсем кажется правильно сделал где нужно из массива сделать еще один массив случайный, но вроде все работает

2021-06-08 06:17 UTC, dtsaryov requested changes

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +const GET_RANDOM_ARRAY_ELEMENT = function (array) {
[Б3. Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.](https://up.htmlacademy.ru/javascript/23/criteries#b3)

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +const GET_RANDOM_ARRAY = function (array) {
[Б3. Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.](https://up.htmlacademy.ru/javascript/23/criteries#b3)

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +// Он иногда почему то вообще выдает пустой массив, с чем это связано?
Ну если массив маленький, то словить "0" при генерации случайного числа проще простого.

ИМХО, это не проблема (если ничего не нарушает ТЗ, конечно)

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +const TYPE = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
[Б5. Массивы названы существительными во множественном числе.](https://up.htmlacademy.ru/javascript/23/criteries#b5)

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +const CHECKIN = ['12:00', '13:00', '14:00'];
[Б5. Массивы названы существительными во множественном числе.](https://up.htmlacademy.ru/javascript/23/criteries#b5)

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +const PHOTOS = [
[Б10. Список констант идёт перед основным кодом.](https://up.htmlacademy.ru/javascript/23/criteries#b5)

Т.е. все объявления функций должны идти после констант

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +const placeAdvert  = function () {
generateAdvert

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +  const LOCATION = {
Это не константа, а неизменяемая переменная, а значит именуется в camelCase

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +      avatar:  `img/avatars/user${  getRandomInt(1, 8)   }.png`,
Куча лишних пробелов

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +      type: GET_RANDOM_ARRAY_ELEMENT(TYPE),//Нужно отдельно создать массив, в котором будут данные palace, flat, house, bungalow или hotel,
Так у тебя ведь уже так сделано сейчас, или я неправильно понял?

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +      guests: getRandomInt(1, 10),
Количество гостей не может быть больше количества комнат по ТЗ

2021-06-08 06:17 UTC, dtsaryov commented on js/main.js
> +      checkout: GET_RANDOM_ARRAY_ELEMENT(CHECKIN),
checkin и checkout по ТЗ должны совпадать

2021-06-08 14:25 UTC, Konstantin9658 commented on js/main.js
> +      type: GET_RANDOM_ARRAY_ELEMENT(TYPE),//Нужно отдельно создать массив, в котором будут данные palace, flat, house, bungalow или hotel,
А это я сначала не понял как надо сделать, а потом сообразил и забыл удалить

2021-06-08 14:27 UTC, Konstantin9658 commented on js/main.js
> +// Он иногда почему то вообще выдает пустой массив, с чем это связано?
В ТЗ вроде ничего не описано, не нашел

2021-06-09 19:28 UTC, dtsaryov requested changes

2021-06-09 19:28 UTC, dtsaryov commented on js/main.js
> +  const choose = getRandomInt(0, 2);// Не знаю правильно ли такое решение?!
`const checkin = getRandomArrayElement(CHECKINS)`

и переиспользуешь уже эту переменную

2021-06-09 19:28 UTC, dtsaryov commented on js/main.js
> +const getRandomArrayElement = function (array) {
Функции на стрелочные все еще не переделал

2021-06-09 20:09 UTC, dtsaryov approved these changes

2021-06-09 20:09 UTC, dtsaryov commented on js/main.js
> +      guests: getRandomInt(1, 3),
Кстати тут тоже можно один раз генерить - не заметил

2021-06-09 20:09 UTC, merged

2021-06-09 20:17 UTC, Konstantin9658 commented on js/main.js
> +      guests: getRandomInt(1, 3),
Ой, и в правду, обязательно исправлю со следующей домашкой